[project]
name = "a2aworkflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a-sdk>=0.3.22",
    "sse-starlette>=3.1.2",
    "starlette>=0.51.0",
    "uvicorn>=0.40.0",
]
